##
## Defines the base image everything is intended to extend. This image contains
## the basic docker components for using consul as a DNS host and resolving
## container names.
##
boot-base:
  container_name: ${DOCKER_BOOT_NAME}
  hostname: ${DOCKER_BOOT_NAME}
  environment:
    DOCKER_BOOT_NAME: ${DOCKER_BOOT_NAME}
  dns:
    - ${DOCKER_CONSUL_IP}
    - 8.8.8.8
    - 8.8.4.4
  dns_search:
    - node.consul
  image: 'apache:2.4'

boot-daemon:
  extends: 'boot-base'
  volumes:
    - ${DOCKER_BOOT_TARGET_DIR}:/var/local/daemon
  expose:
    - 8080
  working_dir: '/var/local/daemon'


##
## Canonical method for running java based applications.
##
boot-jre8:
  extends: 'boot-daemon'
  image: 'java:8-jre'
  command: 'java -jar ${DOCKER_BOOT_NAME}.jar'


##
## Canonical method for running a node based applications.
##
boot-node:
  extends: 'boot-daemon'
  image: 'node:6'
  command: 'node index.js'


##
## Canonical method for running a mysql container.
##
boot-mysql:
  extends: 'boot-base'
  environment:
    MYSQL_ROOT_PASSWORD: ${DOCKER_BOOT_NAME}
    MYSQL_DATABASE: ${DOCKER_BOOT_NAME}
    MYSQL_USER: ${DOCKER_BOOT_NAME}
    MYSQL_PASSWORD: ${DOCKER_BOOT_NAME}
  expose:
    - 3306
  image: 'mysql:5.6'


##
## Canonical method for running an aws-sqs container
##
boot-aws-sqs:
  extends: 'boot-base'
  expose:
    - 4100
  image: 'pafortin/goaws'

##
## Canonical method for running an aws-sns container
##
boot-aws-sns:
  extends: 'boot-aws-sqs'

##
## Canonical method for running an aws-dynamodb container
##
boot-aws-dynamodb:
  extends: 'boot-base'
  expose:
    - 8000
  image: 'deangiberson/aws-dynamodb-local'

##
## Canonincal method for running an hbase container
##
boot-hbase:
  extends: 'boot-base'
  expose:
    - 9095    # thrift webui
    - 9090
    - 8085    # rest webui
    - 8080
    - 2181    # zk
    - 16010   # hbase master
  image: 'dajobe/hbase'

