#!/bin/bash
DOTFILES_ROOT="$HOME/.dotfiles"

print_() {
    echo ""
    echo ""
    echo "---- $1 ----"
    echo ""
    echo ""
}

create_development_directories() {
    print_ "creating development directories"
    mkdir -p ~/Development/projects
    mkdir -p ~/Development/github
    mkdir -p ~/Development/sandbox
    mkdir -p ~/Development/zulu
    mkdir -p ~/Development/auroral
}

link_files() {
    ln -s "$1" "$2"
    echo "linked $1 to $2"
}

install_brew() {
    print_ "installing homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew doctor
}

install_brew_packages() {
    print_ "installing brew packages"
    brew tap homebrew/versions

    brew install tmux
    brew install node
    brew install z
    brew install coreutils
    brew install binutils
    brew install diffutils
    brew install ed --default-names
    brew install findutils --with-default-names
    brew install gawk
    brew install gnu-indent --with-default-names
    brew install gnu-sed --with-default-names
    brew install gnu-tar --with-default-names
    brew install gnu-which --with-default-names
    brew install gnutls
    brew install grep --with-default-names
    brew install gzip
    brew install screen
    brew install watch
    brew install wdiff --with-gettext
    brew install wget
    brew install file-formula
    brew install git
    brew install less
    brew install openssh
    brew install perl518   # must run "brew tap homebrew/versions" first!
    brew install python
    brew install rsync
    brew install svn
    brew install unzip
    brew install vim --override-system-vi
    brew install macvim --override-system-vim --custom-system-icons
    brew install zsh
    brew install gpatch
    brew install bash
    brew install emacs
    brew install m4
    brew install make
    brew install nano
    brew install docker
    brew install docker-machine
    brew install docker-compose
    brew install ag
    brew cask install virtualbox
    brew cask install java
    brew install reattach-to-user-namespace
    brew install dnsmasq
    brew doctor
}

install_3rdparty() {
    sudo gem install jekyll bundler
}

install_vundle() {
    print_ "installing vundle"
    mkdir -p ~/.vim/bundle
    git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/vundle
}

install_vundle_plugins() {
    print_ "installing vundle plugins"
    vim +PluginInstall +qall
}

install_dotfiles() {
    print_ "installing all dotfiles"
    files=$(find "$DOTFILES_ROOT" -maxdepth 2 -name \*.symlink -print)

    for source in $files; do
        file_base=$(basename "${source%.*}")
        dest="$HOME/.$file_base"

        if [ ! -f $dest ]; then
            link_files "$source" "$dest"
        fi
    done
}

#------------------------------#
# BOOTSTRAP
#------------------------------#
create_development_directories
install_brew
install_brew_packages
install_dotfiles
install_vundle
install_vundle_plugins

source ~/.bash_profile
